spring:
  application:
    name: social-login

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: malldbuser
    password: malldbuser
    url: jdbc:mariadb://localhost:3306/malldb

    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 10000

  thymeleaf:
    cache: false

  servlet:
    multipart:
      enabled: true
      location: D:\upload
      max-file-size: 2MB
      max-request-size: 20MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: f994e344488a4e0375f6f9580b14f66d
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
            client-secret: 85st9Asm7o8G1gPSYIGOio9Sb6hKl1RZ
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    com.zaxxer: info
    org.springframework.jdbc: info
    org.springframework.security: info
    org:
      apache:
        ibatis:  debug

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.example.sociallogin.**.dto

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

board:
  upload: D:\upload\attach



